import { Tutor } from './types';

export const TUTOR_TIERS = {
  LEADER: 120000,
  MANAGER: 39000,
  OG: 10000,
};

export const MOCK_TUTORS: Tutor[] = [
  {
    id: 'tutor-kev',
    name: 'Kev',
    avatar: 'https://picsum.photos/seed/kev/200/200',
    rating: 5.0,
    reviewCount: 124,
    specialties: ['Business course', 'Interviewing', 'Test (TOEIC Speaking)', 'Professional English', 'Korean'],
    bio: 'Business English and test preparation expert based in Korea.',
    hourlyRate: TUTOR_TIERS.LEADER,
    availability: ['월 09:00', '월 10:00', '수 15:00', '금 11:00'],
    languages: ['English (Native)', 'Korean'],
    tier: 'Leader',
    location: 'In Korea',
  },
  {
    id: 'tutor-ezeter',
    name: 'Ezeter',
    avatar: 'https://picsum.photos/seed/ezeter/200/200',
    rating: 4.9,
    reviewCount: 89,
    specialties: ['Hungarian', 'Casual', 'High Level'],
    bio: 'High-level casual conversation and Hungarian language expert.',
    hourlyRate: TUTOR_TIERS.LEADER,
    availability: ['화 10:00', '목 14:00', '토 09:00'],
    languages: ['English (Fluent)', 'Hungarian (Native)'],
    tier: 'Leader',
    location: 'In Korea',
  },
  {
    id: 'tutor-derrick',
    name: 'Derrick',
    avatar: 'https://picsum.photos/seed/derrick/200/200',
    rating: 5.0,
    reviewCount: 201,
    specialties: ['Native', 'Any level of English', 'Non Korean speaker'],
    bio: 'USA citizen, native speaker comfortable with any level of English.',
    hourlyRate: TUTOR_TIERS.LEADER,
    availability: ['월 18:00', '수 18:00', '금 18:00'],
    languages: ['English (Native)'],
    tier: 'Leader',
    location: 'Overseas',
  },
  {
    id: 'tutor-lexi',
    name: 'Lexi',
    avatar: 'https://picsum.photos/seed/lexi/200/200',
    rating: 4.9,
    reviewCount: 156,
    specialties: ['Native', 'Any level of English', 'Non Korean speaker'],
    bio: 'USA citizen, native speaker comfortable with any level of English.',
    hourlyRate: TUTOR_TIERS.LEADER,
    availability: ['목 09:00', '금 14:00'],
    languages: ['English (Native)'],
    tier: 'Leader',
    location: 'Overseas',
  },
];
