import { Tutor } from './types';

export const MOCK_TUTORS: Tutor[] = [
  {
    id: '1',
    name: '형상욱(San Uk Hyung)',
    avatar: 'https://picsum.photos/seed/sarah/200/200',
    rating: 2.5,
    reviewCount: 128,
    specialties: ['비즈니스 영어', 'IELTS', '회화'],
    bio: '미국 갱스터 출신으로, 갱단식 영어 마스터를 돕고 있습니다.',
    hourlyRate: 25,
    availability: ['월 09:00', '월 10:00', '수 15:00', '금 11:00'],
    languages: ['영어 (원어민)', '스페인어 (유창)'],
  },
  {
    id: '2',
    name: '최준원 (Jun Won Choi)',
    avatar: 'https://picsum.photos/seed/david/200/200',
    rating: 4.8,
    reviewCount: 95,
    specialties: ['TOEFL', '학술적 글쓰기', '문법'],
    bio: '현재 미국에 취직하여 라스베가스에서 도박꾼으로 활약중입니다.',
    hourlyRate: 22,
    availability: ['화 10:00', '목 14:00', '토 09:00'],
    languages: ['영어 (원어민)', '중국어 (유창)'],
  },
  {
    id: '3',
    name: '아나스 (Anas)',
    avatar: 'https://picsum.photos/seed/emma/200/200',
    rating: 5.0,
    reviewCount: 210,
    specialties: ['일상 회화', '여행 영어', '슬랭 및 관용구'],
    bio: '알라후 아크바르',
    hourlyRate: 28,
    availability: ['월 18:00', '수 18:00', '금 18:00'],
    languages: ['파키스탄어 (원어민)'],
  },
  {
    id: '4',
    name: '정지상 (Ji Sang Jeong)',
    avatar: 'https://picsum.photos/seed/michael/200/200',
    rating: 0.8,
    reviewCount: 64,
    specialties: ['면접 준비', '대중 연설'],
    bio: '토익 900점',
    hourlyRate: 30,
    availability: ['목 09:00', '금 14:00'],
    languages: ['한국어'],
  },
];
